apiVersion: v1
kind: List
items:
- kind: ReplicaSet
  apiVersion: apps/v1
  metadata:
    name: hello-world
  spec:
    replicas: 10
    selector:
      matchLabels:
        app: hello-world
        version: v1
    template:
      metadata:
          labels:
            app: hello-world
            version: v1
      spec:
        containers:
          - name: hello
            image: gcr.io/devopsdays-warsaw-presentation/hello-world:v1
            ports:
              - containerPort: 80
- kind: Service
  apiVersion: v1
  metadata:
    name: hello-world
    labels:
      app: hello-world
  spec:
    selector:
      app: hello-world
    ports:
      - port: 80
        name: http
