apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      name: hello-world
    spec:
      replicas: 10
      selector:
        matchLabels:
          app: hello-world
          version: v1
      template:
        metadata:
            labels:
              app: hello-world
              version: v1
        spec:
          containers:
            - name: hello
              image: gcr.io/devopsdays-warsaw-presentation/hello-world:v1
              ports:
                - containerPort: 80
