kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: hello-world-v1
  labels:
    app: hello-world
    version: v1
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-world
      version: v1
  template:
    metadata:
        labels:
          app: hello-world
          version: v1
    spec:
      containers:
        - name: hello
          image: gcr.io/devopsdays-warsaw-presentation/hello-world:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
